// Özel sipariş hata tipleri
export enum OrderErrorType {
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  STOCK_UNAVAILABLE = 'STOCK_UNAVAILABLE',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  COUPON_INVALID = 'COUPON_INVALID'
} 